// Canonical content source for both React homepage and static export
export const marketingSiteContent = {
  site: {
    name: 'Sangharsh Class',
    tagline: 'From Struggle to Success',
    taglineHindi: 'संघर्ष से सफलता तक',
    logo: '/assets/IMG-20260201-WA0000.jpg',
    domain: 'https://sangharshclasses.in/',
  },
  hero: {
    heading: 'Sangharsh Classes',
    headingHindi: 'SSC, Railway & Banking Coaching in Muzaffarpur, Bihar',
    guaranteeBadge: '100% Result Guarantee',
    description: 'Quality Education for Class 7th to 12th with Expert Faculty and Result-Oriented Teaching',
    ctaPrimary: 'Enroll Now',
    ctaSecondary: 'View Courses',
    backgroundImage: '/assets/generated/hero-banner.dim_1200x600.jpg',
    stats: [
      { icon: 'Users', value: '500+', label: 'Students Enrolled' },
      { icon: 'Award', value: '4+ Years', label: 'Teaching Excellence' },
      { icon: 'TrendingUp', value: '100%', label: 'Result Oriented' },
    ],
  },
  about: {
    heading: 'About Sangharsh Classes',
    paragraphs: [
      'Sangharsh Classes ek trusted coaching institute hai, jahan students ko quality education ke saath strong results milte hain। Yahan padhne wale bahut se students ne achhe numbers se exams pass kiye hain aur apni academic performance ko kaafi improve kiya hai।',
      'Hamari coaching ka main focus concept clear karna, regular practice aur result-oriented teaching par hota hai। Sangharsh Classes me 5 experienced aur dedicated teachers hain, jo har student par personal attention dete hain, taaki koi bhi bachcha padhai me pichhe na rahe।',
      'Hum simple language me padhate hain, doubt clear classes rakhte hain aur students ko exam ke liye proper guidance, notes aur test practice dete hain। Yahi wajah hai ki parents aur students dono ka hum par bharosa bana hua hai।',
      'Sangharsh Classes – Jahan mehnat ka milta hai sahi result.',
    ],
    seoDescription: [
      'Sangharsh Classes is a premier coaching institute located in Muzaffarpur, Bihar, dedicated to providing top-quality education for SSC, Railway, and Banking exam preparation. With over 4 years of teaching excellence and a proven track record of success, we have established ourselves as one of the most trusted coaching centers in the region. Our institute specializes in comprehensive exam preparation that combines conceptual clarity with practical problem-solving skills, ensuring that every student achieves their career goals.',
      'At Sangharsh Classes, we understand the competitive nature of government job exams like SSC CGL, SSC CHSL, Railway RRB NTPC, Railway Group D, IBPS PO, IBPS Clerk, and SBI exams. Our experienced faculty members bring years of expertise in their respective subjects, offering personalized attention to each student. We believe that success in competitive exams requires not just hard work but also smart preparation strategies, regular practice, and proper guidance – all of which form the core of our teaching methodology.',
      'Our coaching programs are designed to cater to students from diverse educational backgrounds. Whether you are a fresh graduate preparing for your first government job exam or a working professional looking to switch careers, Sangharsh Classes provides the right environment and resources for your success. We offer both offline classroom coaching and comprehensive study materials that cover the entire syllabus of SSC, Railway, and Banking exams. Our classes are conducted in a student-friendly manner, with emphasis on concept building, time management, and exam-oriented preparation.',
      'What sets Sangharsh Classes apart from other coaching institutes in Muzaffarpur is our result-oriented approach. We don\'t just teach; we ensure that our students understand every concept thoroughly and can apply their knowledge effectively in exams. Our faculty conducts regular doubt-clearing sessions, provides personalized feedback, and tracks each student\'s progress through periodic tests and assessments. We also offer special crash courses and revision programs before major exams to help students consolidate their preparation.',
      'Located conveniently at Speaker Chowk, Mai Sthan Gali, Muzaffarpur, our institute is easily accessible from all parts of the city. We maintain small batch sizes to ensure quality education and individual attention. Our affordable fee structure makes quality coaching accessible to students from all economic backgrounds. We believe that financial constraints should never be a barrier to quality education and career success.',
      'Join Sangharsh Classes today and take the first step towards your dream government job. With our experienced faculty, comprehensive study materials, regular mock tests, and proven teaching methodology, we are committed to helping you succeed in SSC, Railway, and Banking exams. Admissions are now open for new batches. Contact us at 9262647420 or visit our institute to learn more about our courses and enrollment process. Your journey from struggle to success begins here at Sangharsh Classes, Muzaffarpur.',
    ],
    feature: {
      icon: 'Target',
      title: 'Result Oriented',
      description: 'Our teaching methodology is focused on delivering excellent results and helping students achieve their academic goals.',
    },
  },
  faculty: [
    {
      photoUrl: '/assets/362649410_827011885318636_8020958095991400208_n.jpg',
      name: 'Sorav Sir',
      subject: 'Physics',
      experience: '4+ Years',
      role: 'Physics Expert',
      specialization: 'Specialized in Physics with proven teaching methodologies',
    },
    {
      photoUrl: '/assets/479492974_1291555798632827_4485357872493306414_n.jpg',
      name: 'Dr Raju Raushan',
      subject: 'Mathematics',
      experience: '4+ Years',
      role: 'Mathematics Expert',
      specialization: 'Specialized in mathematics with proven teaching methodologies',
    },
  ],
  courses: [
    {
      id: 7,
      name: 'Class 7th',
      description: 'Foundation building with focus on core concepts in Mathematics, Science, and other subjects',
      features: ['Expert Faculty', 'Board Exam Focus', 'Regular Tests'],
    },
    {
      id: 8,
      name: 'Class 8th',
      description: 'Strengthening fundamentals and developing problem-solving skills across all subjects',
      features: ['Expert Faculty', 'Board Exam Focus', 'Regular Tests'],
    },
    {
      id: 9,
      name: 'Class 9th',
      description: 'Board exam preparation begins with comprehensive coverage of CBSE/State Board syllabus',
      features: ['Expert Faculty', 'Board Exam Focus', 'Regular Tests'],
    },
    {
      id: 10,
      name: 'Class 10th',
      description: 'Intensive board exam preparation with regular tests and doubt-clearing sessions',
      features: ['Expert Faculty', 'Board Exam Focus', 'Regular Tests'],
    },
    {
      id: 11,
      name: 'Class 11th',
      description: 'Advanced concepts in PCM with focus on competitive exam preparation alongside boards',
      features: ['Expert Faculty', 'Board Exam Focus', 'Regular Tests'],
    },
    {
      id: 12,
      name: 'Class 12th',
      description: 'Final year board preparation with emphasis on scoring high marks and concept clarity',
      features: ['Expert Faculty', 'Board Exam Focus', 'Regular Tests'],
    },
  ],
  coursesExtra: {
    heading: 'Specialized Board Exam Preparation',
    description: 'Our courses are meticulously designed to build strong conceptual foundations while ensuring excellent board exam results. We focus on both understanding and application.',
    subjects: ['Mathematics', 'Physics', 'Chemistry'],
  },
  contact: {
    phone: '9262647420',
    email: 'govindofficial027@gmail.com',
    location: 'Speaker Chowk, Mai Sthan Gali, Muzaffarpur',
    backgroundImage: '/assets/generated/academic-success-bg.dim_800x400.jpg',
  },
  footer: {
    description: 'From Struggle to Success - Quality education for Class 7th to 12th with expert faculty and 100% result guarantee.',
    quickLinks: ['Home', 'About', 'Faculty', 'Courses', 'Contact'],
    social: [
      { platform: 'Facebook', url: 'https://www.facebook.com/share/173TNduUtd/', icon: 'SiFacebook' },
      { platform: 'Instagram', url: 'https://www.instagram.com/rajooraushan?igsh=cmUycTB5ZmZ6MjRi', icon: 'SiInstagram' },
      { platform: 'YouTube', url: 'https://youtube.com/@sangharshclassesmuzaffarpur?si=qZaASH_gn1aY5Y8I', icon: 'SiYoutube' },
    ],
    copyright: '© 2026 Govind Kumar | Web Developer',
  },
  navigation: [
    { label: 'Home', id: 'hero' },
    { label: 'About', id: 'about' },
    { label: 'Faculty', id: 'faculty' },
    { label: 'Courses', id: 'courses' },
    { label: 'Contact', id: 'contact' },
  ],
};
